---
kind: pipeline
type: kubernetes
name: default

steps:
- name: triggered-by-a
  image: python:3.4
  commands:
  - pytest
  when:
    paths:
      include:
        - folder_a/**
    branch:
      - main
    event:
      - push

- name: triggered-by-b
  image: python:3.4
  commands:
  - pytest
  when:
    paths:
      include:
        - folder_b/**
    branch:
      - main
    event:
      - push

- name: triggered-by-everything-else
  image: python:3.4
  commands:
  - pytest
  when:
    paths:
      exclude:
        - folder_a/**
        - folder_b/**
    branch:
      - main
    event:
      - push
