---
kind: pipeline
type: kubernetes
name: default

steps:
- name: triggered-by-a
  image: plugins/kaniko-ecr
  settings:
    create_repository: true
    registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
    repo: devops/${DRONE_REPO_NAME}
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}
    - latest
    access_key:
      from_secret: ecr_access_key
    secret_key:
      from_secret: ecr_secret_key
  when:
    paths:
      include:
        - folder_a/**
    branch:
      - main
    event:
      - push

- name: triggered-by-anything-except-a
  image: plugins/kaniko-ecr
  settings:
    create_repository: true
    registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
    repo: devops/${DRONE_REPO_NAME}
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}
    - latest
    access_key:
      from_secret: ecr_access_key
    secret_key:
      from_secret: ecr_secret_key
  when:
    paths:
      exclude:
        - folder_a/**
    branch:
      - main
    event:
      - push
